### ISSUE TITLE
How to update to the last version

### ISSUE THREAD

**Issue by jorge-delgado-aera** [exasol/cloudwatch-adapter#62]
Hello, do you have the steps to implement below metrics or last version of cloudwatch adapter?

https://github.com/exasol/cloudwatch-adapter/blob/main/doc/changes/changes_1.0.0.md#cloudwatch-adapter-100-released-2022-02-23

**Comment by jakobbraun** [comment]
Thanks for pointing out. We just realized that our deployment process is broken, so the version available in the AWS serverless app repository is outdated.
We try to fix this as soon as possible.

Once we published the latest version you can upgrade. Updating a AWS serverless app is basically just overriding it: https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-how-to-consume-new-version.html


If you don't want to wait you can checkout this repo and deploy it manually: https://github.com/exasol/cloudwatch-adapter#information-for-developers

**Comment by jorge-delgado-aera** [comment]
hello @jakobbraun, just for this I have 2 questions:

1.- Is planned to update this tool frecuently?, just I want to know to consider this as an official tool for monitoring
2.- Do you know when last version will be deployed?

THANKS IN ADVANCE.

**Comment by jakobbraun** [comment]
Hi,
yes we plan to maintain this tool. We also did invest into updates and just due to the broken release mechanism did not deploy them to the store.
You can expect a release of the latest version later today.

**Comment by jakobbraun** [comment]
We now published the latest version 1.0.1 on AWS. 
Sorry again for the inconvenience.

**Comment by jorge-delgado-aera** [comment]
hi @jakobbraun, thanks for the last update for the tool, previously I saw 32 metrics collected, but after the upgrade I still see the same 32 metrics, do I need to perform anything else to see backup metrics?, below the link for metrics that I refer to.

[https://github.com/exasol/cloudwatch-adapter/blob/main/doc/changes/changes_1.0.0.md#cloudwatch-adapter-100-released-2022-02-23](url)

thanks for your help.

**Comment by kaklakariada** [comment]
Hi @jorge-delgado-aera ,
It's possible that no backup events occurred since you installed the new version. The cloudwatch-adapter only adds metrics when the corresponding events are found in the database. Please check if you find recent rows with `EVENT_TYPE` value `BACKUP_START` or `BACKUP_END` in table [EXA_SYSTEM_EVENTS](https://docs.exasol.com/saas/sql_references/system_tables/statistical/exa_system_events.htm):

```sql
select *
from EXA_SYSTEM_EVENTS
where event_type like 'BACKUP%'
order by measure_time desc;
```

**Comment by jorge-delgado-aera** [comment]
hi @kaklakariada, I checked with the above query and it retrieves data updated, I will open a ticket for following up

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/90013150/166459469-1c3e28b0-2818-4782-82d6-11d19bdaf61a.png">
